# --- The Canvas ---
background            #14171f
foreground            #cbd5e0
selection_background  #3d475f
selection_foreground  #cbd5e0
url_color             #52becc
cursor                #cbd5e0
cursor_text_color     #14171f

# --- Tabs & Borders ---
active_tab_foreground   #14171f
active_tab_background   #52becc
inactive_tab_foreground #939bad
inactive_tab_background #1c1c1c
active_border_color     #52becc
inactive_border_color   #1c1c1c

# --- ANSI Colors (The 16-color Palette) ---

# Black (Use your charcoal and bg_lighter)
color0 #1c1c1c
color8 #3d475f

# Red
color1 #FFC0B9
color9 #FFC0B9

# Green
color2 #7cc080
color10 #7cc080

# Yellow/Orange (Matches your Constants/Booleans)
color3 #FCE094
color11 #d7935b

# Blue (Mapping Cyan/Slate here)
color4 #52becc
color12 #718096

# Magenta (Using Cream/Grey here)
color5 #ffeab7
color13 #939bad

# Cyan
color6 #52becc
color14 #52becc

# White
color7 #cbd5e0
color15 #ffffff
