# Yesterday Bright dark theme
background #343d46
foreground #dfe1e8

cursor #dfe1e8
cursor_text_color #343d46

selection_background #65737e
selection_foreground #dfe1e8

url_color #7aa6da

# tab bar
tab_bar_background #4f5b66
active_tab_background #a7adba
active_tab_foreground #ffffff
inactive_tab_background #4f5b66
inactive_tab_foreground #a7adba

# black
color0  #343d46
color8  #a7adba

# red
color1  #d54e53
color9  #d54e53

# green
color3  #b9ca4a
color11 #b9ca4a

# yellow
color2  #e7c547
color10 #e7c547

# blue
color4  #7aa6da
color12 #7aa6da

# magenta
color5  #c397d8
color13 #c397d8

# cyan
color6  #70c0b1
color14 #70c0b1

# white
color7  #dfe1e8
color15 #ffffff
